### ISSUE TITLE
Spelling: 'aspect' and 'sequitur'

### ISSUE THREAD

**Issue by matt-dray** [sharlagelfand/understanding-comics#1]
Hi Sharla, this is very cool. I look forward to more viz.

A minor observation: I think there may be a couple of misspellings on the left-hand bar. Should categories 5 and 6 be 'a**s**pect-to-aspect' and 'non-sequit**u**r'?

**Comment by sharlagelfand** [comment]
yep you're right, thanks! hard to catch spelling once you've stared at something for so long. fixed!
